project:
  type: website
  output-dir: "docs"

date-format: iso
theme:
  light: flatly
  dark: darkly

website:
  title: "職務経歴書"
  site-url: "https://i9wa4.github.io/resume/"
  favicon: "./assets/icon_hhkb2.jpg"
  search: true

format:
  html:
    toc: true
    toc-depth: 2
    toc-expand: 2
    toc-title: "TOC"
    toc-location: right
    page-layout: full
    linestretch: 1.4
