project:
  type: website
  output-dir: docs

website:
  title: "職務経歴書"
  site-url: "https://i9wa4.github.io/resume/"
  navbar:
    right:
      - icon: github
        href: https://github.com/i9wa4
      - icon: twitter-x
        href: https://x.com/i9wa4_

format:
  html:
    toc: true
    toc-depth: 2
    toc-expand: 2
    toc-title: TOC
    toc-location: right

date: last-modified
date-format: iso
theme: flatly
