project:
  type: website
  output-dir: docs

website:
  title: "職務経歴書"
  site-url: "https://i9wa4.github.io/resume/"

format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: 目次
    toc-location: right

lang: ja
date: last-modified
date-format: iso
theme: flatly
