project:
  type: website
  output-dir: "out"

date-format: iso
theme:
  # https://quarto.org/docs/output-formats/html-themes.html
  light: yeti
  dark: superhero

website:
  title: "職務経歴書"
  site-url: "https://i9wa4.github.io/resume/"
  search: false
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "職務経歴 詳細"
        href: "./details/index.qmd"
        contents:
          - "./details/06-sinkcapital.qmd"
          - "./details/05-genda.qmd"
          - "./details/04-hacomono.qmd"
          - "./details/03-cnsh.qmd"
          - "./details/02-sld.qmd"
          - "./details/01-okuma.qmd"


format:
  html:
    page-layout: full
    toc: true
    toc-depth: 2
    toc-expand: true
    toc-title: "Table of Contents"
    linestretch: 1.4
