project:
  type: website
  output-dir: "_site"

date-format: iso
theme:
  # https://quarto.org/docs/output-formats/html-themes.html
  light: yeti
  dark: superhero

website:
  title: "職務経歴書"
  bread-crumbs: true
  page-navigation: false
  search: false
  sidebar:
    style: floating
    contents:
      - section: "職務経歴 詳細"
        href: "details/index.qmd"
        contents:
          # - "details/06-pivot.qmd"
          - "details/05-genda.qmd"
          - "details/04-hacomono.qmd"
          - "details/03-cnsh.qmd"
          - "details/02-sld.qmd"
          - "details/01-okuma.qmd"
      - text: "---"
      - section: "My Other Websites"
        contents:
          - href: "https://i9wa4.github.io/i9wa4"
            text: "About"
          - href: "https://i9wa4.github.io"
            text: "My Page"
      - text: "---"
      - section: "External Links"
        contents:
          - href: "https://github.com/i9wa4"
            text: "GitHub"
          - href: "https://x.com/i9wa4_"
            text: "X (Twitter)"
          - href: "https://www.linkedin.com/in/daikm/"
            text: "LinkedIn"
          - href: "https://zenn.dev/i9wa4"
            text: "Zenn"

format:
  html:
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    linestretch: 1.4
    page-layout: full
    toc-depth: 2
    toc-expand: true
    toc-title: "Table of Contents"
    toc: true
