project:
  type: website
  output-dir: docs

website:
  title: "職務経歴書"
  site-url: "https://i9wa4.github.io/resume/"
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)"
    center: "&copy;2024, i9wa4"
    right:
      - icon: github
        href: https://github.com/i9wa4
      - icon: twitter
        href: https://x.com/i9wa4_

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-title: TOC
    toc-location: right

lang: ja
date: last-modified
date-format: "YYYY-MM-DD"
