---
title: "職務経歴 新光商事LSIデザインセンター株式会社"
date: last-modified
repo-actions: false
---

:会社概要・雇用形態 (2022年時点) {#tbl-company tbl-colwidths="[20,80]"}

|              |                                                            |
| :---         | :---                                                       |
| 事業内容     | 組込ソフトウェア開発、ASIC/FPGA 開発                       |
| 資本金       | 8000万円                                                   |
| 売上高       | 16.7億円                                                   |
| 従業員数     | 83名                                                       |
| 上場／非上場 | 非上場                                                     |
| 勤務地       | 北海道札幌市<br>2020年3月以降は週に約3回リモートワーク実施 |
| 雇用形態     | 正社員                                                     |
| 所属         | [2018/08 - 2022/03] ソフト開発一部 開発二課                |

<!--
**入社動機**
- 最優先事項として札幌拠点で働くことを掲げていました。
- 前職ではプログラムを全く書かないエンジニアだったため、プログラムを自分で書けることを優先しました。
- 業界としては実際にモノを動かすことができて経歴上親しみのある組み込み業界としました。
- 業務に必要な現代制御を学んでいくことに好奇心が湧き、楽しく業務を続けられるイメージが湧きました。

**退職動機**
- テレワークを行うようになり、今後のライフスタイルを考慮しフルリモート勤務が可能な分野で成長していこうと考えました。
- C言語でプログラムを書くという技術的に新規性の少ない作業に飽きがきていた。
-->

以下、新しい順にプロジェクトを記載しております。

## 1. 親会社向け車両通信プロトコル解説講義

### 1.1. 期間

- 2022/02 - 2022/03

### 1.2. 担当業務

- 車両組込システムの通信プロトコル (CAN) の説明資料作成
- 組込システムへのCAN通信実装
- 上記を利用した講義実施

### 1.3. 担当フェーズ

- なし

### 1.4. 開発環境

- C
- アセンブラ
- Renesas CS+ V8.05.00
- RH850/C1M-A1

### 1.5. 規模・役割

- 2名
- メンバー

## 2. 噴霧器システム開発

### 2.1. 期間

- 2021/06 - 2022/01

### 2.2. 担当業務

- プロトタイプ向け汎用インバータ制御開発
- 顧客インバータ制御開発
- 噴霧器の操作器開発

### 2.3. 実績・取り組み

- 顧客要望で解析用グラフ資料作成業務が発生した際に、自主的に習得していたPythonを用いて満足いただける資料を作成できました。

### 2.4. 担当フェーズ

- 要件分析
- 基本設計
- 詳細設計
- 開発

### 2.5. 開発環境

- C
- アセンブラ
- Renesas CS+ V8.05.00
- RL78/G1F
- RL78/G12

### 2.6. 規模・役割

- 4名
- メンバー

## 3. 車両緊急通報システムのマイコン移植

### 3.1. 期間

- 2020/10 - 2021/05

### 3.2. 担当業務

- マイコン移植による故障懸念点の洗い出し
- マイコンのリソース割当検討
- 各種タイマ機能とシリアル通信機能の移植
- テスト仕様書作成
- テスト実施

### 3.3. 実績・取り組み

- 5名が各々実施していた30以上のテスト仕様書のフォーマット整備をExcel VBAで自動化することで全員の負担を軽減し、特に経験の浅い1名の負担軽減に大きく貢献できました。

### 3.4. 担当フェーズ

- 要件分析
- 基本設計
- 詳細設計
- 開発
- テスト

### 3.5. 開発環境

- C
- アセンブラ
- GHS MULTI V2020.1.5
- QAC 7.2.3
- RH850/F1K

### 3.6. 規模・役割

- 9名
- メンバー

## 4. 自動車トラクション制御ファームウェアの無線更新機能の開発

#### 4.0.1. 期間

- 2020/04 - 2020/09

### 4.1. 担当業務

- バックアップ・更新処理の設計開発
- カバレッジテスト・単体テスト・結合テストの仕様書作成
- テスト実施

### 4.2. 担当フェーズ

- 要件分析
- 基本設計
- 詳細設計
- 開発
- テスト

### 4.3. 開発環境

- C
- アセンブラ
- GHS MULTI V2013.5.5
- QAC 8.1.1J
- winAMS v6.3.1
- RH850/C1M

### 4.4. 規模・役割

- 8名
- メンバー

## 5. 自動車トラクション制御開発用ファームウェアの更新機能開発

### 5.1. 期間

- 2019/10 - 2020/03

### 5.2. 担当業務

- トラクションモータ開発基板側の通信機能・自身のROM書き換え機能の設計開発
- PCアプリ含めたシステムのテスト仕様作成
- テスト実施

### 5.3. 担当フェーズ

- 要件分析
- 基本設計
- 詳細設計
- 開発
- テスト

### 5.4. 開発環境

- C
- アセンブラ
- GHS MULTI  V2015.1.7
- RH850/C1M-A1

### 5.5. 規模・役割

- 6名
- メンバー
