---
title: "職務経歴 新光商事LSIデザインセンター株式会社"
---

## 1. 会社概要・雇用形態 (2022年時点)

- 事業内容
    - 組込ソフトウェア開発、ASIC/FPGA 開発
- 資本金
    - 8000万円
- 売上高
    - 16.7億円
- 従業員数
    - 83名
- 上場／非上場
    - 非上場
- 雇用形態
    - 正社員
- 勤務地
    - 北海道札幌市

## 2. プロジェクト一覧

新しい順に記載しております。

### 2.1. 親会社向け車両通信プロトコル解説講義

#### 2.1.1. 期間

- 2022年2月-3月

#### 2.1.2. 担当業務

- 車両組込システムの通信プロトコル (CAN) の説明資料作成
- 組込システムへのCAN通信実装
- 上記を利用した講義実施

#### 2.1.3. 担当フェーズ

- なし

#### 2.1.4. 開発環境

- C
- アセンブラ
- Renesas CS+ V8.05.00
- RH850/C1M-A1

#### 2.1.5. 規模・役割

- 2名
- メンバー

### 2.2. 噴霧器システム開発

#### 2.2.1. 期間

- 2021年6月-2022年1月

#### 2.2.2. 担当業務

- プロトタイプ向け汎用インバータ制御開発
- 顧客インバータ制御開発
- 噴霧器の操作器開発

#### 2.2.3. 実績・取り組み

- 顧客要望で解析用グラフ資料作成業務が発生した際に、自主的に習得していたPythonを用いて満足いただける資料を作成できました。

#### 2.2.4. 担当フェーズ

- 要件分析
- 基本設計
- 詳細設計
- 開発

#### 2.2.5. 開発環境

- C
- アセンブラ
- Renesas CS+ V8.05.00
- RL78/G1F
- RL78/G12

#### 2.2.6. 規模・役割

- 4名
- メンバー

### 2.3. 車両緊急通報システムのマイコン移植

#### 2.3.1. 期間

- 2020年10月-2021年5月

#### 2.3.2. 担当業務

- マイコン移植による故障懸念点の洗い出し
- マイコンのリソース割当検討
- 各種タイマ機能とシリアル通信機能の移植
- テスト仕様書作成
- テスト実施

#### 2.3.3. 実績・取り組み

- 5名が各々実施していた30以上のテスト仕様書のフォーマット整備をExcel VBAで自動化することで全員の負担を軽減し、特に経験の浅い1名の負担軽減に大きく貢献できました。

#### 2.3.4. 担当フェーズ

- 要件分析
- 基本設計
- 詳細設計
- 開発
- テスト

#### 2.3.5. 開発環境

- C
- アセンブラ
- GHS MULTI V2020.1.5
- QAC 7.2.3
- RH850/F1K

#### 2.3.6. 規模・役割

- 9名
- メンバー

### 2.4. 自動車トラクション制御ファームウェアの無線更新機能の開発

##### 2.4.0.1. 期間

- 2020年4月-9月

#### 2.4.1. 担当業務

- バックアップ・更新処理の設計開発
- カバレッジテスト・単体テスト・結合テストの仕様書作成
- テスト実施

#### 2.4.2. 担当フェーズ

- 要件分析
- 基本設計
- 詳細設計
- 開発
- テスト

#### 2.4.3. 開発環境

- C
- アセンブラ
- GHS MULTI V2013.5.5
- QAC 8.1.1J
- winAMS v6.3.1
- RH850/C1M

#### 2.4.4. 規模・役割

- 8名
- メンバー

### 2.5. 自動車トラクション制御開発用ファームウェアの更新機能開発

#### 2.5.1. 期間

- 2019年10月-2020年3月

#### 2.5.2. 担当業務

- トラクションモータ開発基板側の通信機能・自身のROM書き換え機能の設計開発
- PCアプリ含めたシステムのテスト仕様作成
- テスト実施

#### 2.5.3. 担当フェーズ

- 要件分析
- 基本設計
- 詳細設計
- 開発
- テスト

#### 2.5.4. 開発環境

- C
- アセンブラ
- GHS MULTI  V2015.1.7
- RH850/C1M-A1

#### 2.5.5. 規模・役割

- 6名
- メンバー
