---
title: "職務経歴 株式会社hacomono"
---

**作成中**

:会社概要・雇用形態 (2024年時点) {#tbl-company tbl-colwidths="[20,80]"}

|              |                                                                                    |
| ---          | ---                                                                                |
| 事業内容     | 月額型店舗のための会員管理・予約・キャッシュレス決済システム「hacomono」開発・販売 |
| 資本金       | 100百万円                                                                          |
| 売上高       | 非公開                                                                             |
| 従業員数     | 217名                                                                              |
| 上場／非上場 | 非上場                                                                             |
| 雇用形態     | 正社員                                                                             |
| 勤務地       | フルリモート (居住地 北海道札幌市)<br>年に数回東京原宿本社へ出社                   |

以下、新しい順にプロジェクトを記載しております。

## 1. プロジェクト以外の社内業務

### 1.1. 社内テックブログ執筆

- [2024/07/02]

## 2. 顧客 BigQuery 環境へのストリーム転送機能開発・運用

### 2.1. 概要

### 2.2. 期間

- 2024/04 - 現在

### 2.3. 規模・役割

- [2024/04 - 2024/05]
    - 役割：メンバー
    - 規模：2名
- [2024/06 - 現在]
    - 役割：リーダー
    - 規模：1名

### 2.4. 担当業務

1. [2024/04 - 2024/05] (2名) 定常運用業務・業務引き継ぎ
1. [2024/06 - 現在] (私1名) 上記に加えて運用改善業務

### 2.5. 機能開発・実装詳細

### 2.6. 目的・背景

### 2.7. 課題

### 2.8. 工夫した点

### 2.9. 成果

### 2.10. 担当フェーズ

- 基本設計
- 詳細設計
- 開発
- テスト
- 運用
- 保守

### 2.11. 開発環境

- GitHub
- Terraform
- AWS
    - RDS (MySQL)
    - VPC
- Google Cloud
    - BigQuery
    - Datastream

## 3. 顧客 BigQuery 環境構築・運用 (バッチ転送)

### 3.1. 概要

- バッチ処理

### 3.2. 期間

- 2024/04 - 現在

### 3.3. 規模・役割

- [2024/04 - 2024/05]
    - 役割：メンバー
    - 規模：2名
- [2024/06 - 現在]
    - 役割：リーダー
    - 規模：1名

### 3.4. 担当業務

1. [2024/04 - 2024/05] (2名) 定常運用業務・業務引き継ぎ
1. [2024/06 - 現在] (私1名) 上記に加えて運用改善業務

### 3.5. 機能開発・実装詳細

### 3.6. 目的・背景

### 3.7. 課題

### 3.8. 工夫した点

### 3.9. 成果

### 3.10. 担当フェーズ

- 運用
- 保守

### 3.11. 開発環境

- GitHub
- Terraform
- Embulk
- AWS
    - ECS
    - RDS (MySQL)
    - Aurora (MySQL)
    - VPC
- Google Cloud
    - BigQuery

## 4. 社内 BigQuery 環境構築・運用

### 4.1. 概要

- 自社サービスのシングルテナント・マルチテナント環境 RDB から BigQuery へデータを転送し DWH を作成するシステムの運用・保守

### 4.2. 期間

- 2024/04 - 現在

### 4.3. 規模・役割

- [2024/04 - 2024/05]
    - 役割：メンバー
    - 規模：2名
- [2024/06 - 現在]
    - 役割：リーダー
    - 規模：1名

### 4.4. 担当業務

1. [2024/04 - 2024/05] (2名) 定常運用業務・業務引き継ぎ
1. [2024/06 - 現在] (私1名) 上記に加えて運用改善業務

### 4.5. 機能開発・実装詳細

### 4.6. 目的・背景

### 4.7. 課題

### 4.8. 工夫した点

### 4.9. 成果

### 4.10. 担当フェーズ

- 運用
- 保守

### 4.11. 開発環境

- GitHub
- Terraform
- Embulk
- AWS
    - ECS
    - RDS (MySQL)
    - Aurora (MySQL)
    - VPC
- Google Cloud
    - BigQuery
